#!/usr/bin/env python3
"""PreToolUse guard: turns the AGENTS.md rules agents most often forget into tool decisions.

Claude Code pipes the pending tool call to stdin as JSON. This script prints a PreToolUse
decision to stdout, or nothing at all when it has no opinion, in which case the normal
permission flow applies. It never exits non-zero on its own bugs: a broken guard must not
brick the session, so unexpected errors fall through to "no opinion".

What it decides — ADR-0007 records why each one is here:

  ask   Edit/Write to a protected file          AGENTS.md § 1 "Protected files"
  ask   a Bash command that writes one          (sed -i, tee, >, mv, cp, rm …)
  deny  Edit/Write to frontend/AGENTS.md        generated by `next dev`; edits are lost
  deny  a Bash command that prints a .env file  AGENTS.md § 1 rule 6
  deny  a git commit message that breaks § 4    format, or an AI-attribution line
  deny  history rewriting                       push --force, reset --hard, --no-verify,
                                                branch -D, push --delete, filter-branch

The protected list and the commit types are read from AGENTS.md itself, so the contract
stays the single source of truth (ADR-0006). If AGENTS.md cannot be parsed, the guard
falls back to a built-in list rather than protecting nothing.

Bash parsing is best-effort. It covers the command forms an agent actually writes; it is
a guard rail, not a security boundary.

Self-test: python3 .claude/hooks/test_agent_guard.py
"""

from __future__ import annotations

import json
import os
import re
import shlex
import sys
from pathlib import Path

PROJECT_DIR = Path(os.environ.get("CLAUDE_PROJECT_DIR") or Path(__file__).resolve().parents[2])
CONTRACT = PROJECT_DIR / "AGENTS.md"

FALLBACK_PROTECTED = {
    "AGENTS.md",
    "CLAUDE.md",
    ".env",
    ".env.example",
    ".gitignore",
    ".editorconfig",
    "LICENSE",
    "backend/config/settings.py",
    "backend/pyproject.toml",
    "frontend/next.config.ts",
    "frontend/tsconfig.json",
    "frontend/package.json",
}
FALLBACK_TYPES = ("feat", "fix", "docs", "refactor", "test", "chore", "perf", "style", "build")

GENERATED = {"frontend/AGENTS.md"}
SUBJECT_MAX = 72

# A .env file holds real values; .env.example holds placeholders and is safe to read.
ENV_FILE = re.compile(r"(^|/)\.env(\.[\w.-]+)?$")
ENV_SAFE = re.compile(r"(^|/)\.env\.example$")
ENV_READERS = {"cat", "less", "more", "head", "tail", "bat", "strings", "xxd", "od", "nl", "tac"}

AI_ATTRIBUTION = re.compile(
    r"^\s*co-authored-by:.*\b(claude|anthropic|openai|chatgpt|gpt|copilot|gemini|codex|cursor"
    r"|devin|aider|codeium|windsurf)\b"
    r"|generated (with|by) \[?(claude|copilot|chatgpt|gpt|gemini|codex|cursor)\b"
    r"|\U0001f916"
    r"|claude\.com/claude-code|claude\.ai/code\b",
    re.IGNORECASE | re.MULTILINE,
)

SEPARATOR_CHARS = set(";&|()\n")
WRITE_REDIRECTS = {">", ">>", "&>", ">|"}
HEREDOC = re.compile(r"<<-?[ \t]*(['\"]?)([A-Za-z_][A-Za-z0-9_]*)\1[^\n]*\n(.*?)\n[ \t]*\2[ \t]*(?=\n|$)", re.S)
CAT_HEREDOC = re.compile(r"^\$\(\s*cat\s+<<-?\s*['\"]?(\w+)['\"]?\s*\n(.*)\n\s*\1\s*\)\s*$", re.S)


# ── reading the contract ────────────────────────────────────────────────────────────────


def _contract_text() -> str:
    try:
        return CONTRACT.read_text(encoding="utf-8")
    except OSError:
        return ""


def protected_files() -> set[str]:
    text = _contract_text()
    match = re.search(r"\*\*Protected files[^*]*\*\*(.*?)(?:\n\s*\n)", text, re.S)
    if not match:
        return set(FALLBACK_PROTECTED)
    names = set(re.findall(r"`([^`\s]+)`", match.group(1)))
    return names or set(FALLBACK_PROTECTED)


def is_protected(rel: str | None, protected: set[str]) -> bool:
    """A listed path matches exactly; a bare file name (`.env`, `CLAUDE.md`) matches at any depth."""
    if rel is None:
        return False
    if rel in protected or rel in GENERATED:
        return True
    name = rel.rsplit("/", 1)[-1]
    return any("/" not in entry and entry == name for entry in protected)


def commit_types() -> tuple[str, ...]:
    match = re.search(r"^Types:\s*(.+)$", _contract_text(), re.M)
    types = tuple(re.findall(r"`([a-z]+)`", match.group(1))) if match else ()
    return types or FALLBACK_TYPES


# ── decisions ───────────────────────────────────────────────────────────────────────────


def decision(kind: str, reason: str) -> dict:
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": kind,
            "permissionDecisionReason": reason,
        }
    }


def relative(path: str, cwd: str | None = None) -> str | None:
    """Repo-relative POSIX path, or None when the path is outside the project."""
    if not path:
        return None
    candidate = Path(path)
    if not candidate.is_absolute():
        candidate = Path(cwd or PROJECT_DIR) / candidate
    try:
        resolved = candidate.resolve(strict=False)
        return resolved.relative_to(PROJECT_DIR.resolve()).as_posix()
    except (ValueError, OSError):
        return None


def check_file_tool(tool_input: dict, cwd: str | None) -> dict | None:
    rel = relative(tool_input.get("file_path") or tool_input.get("notebook_path") or "", cwd)
    if rel is None:
        return None
    if rel in GENERATED:
        return decision(
            "deny",
            f"{rel} is generated by `next dev` and rewritten on its next run (AGENTS.md § 1). "
            "Put frontend rules in AGENTS.md or documentation/system-design/NEXTJS_STANDARDS.md.",
        )
    if is_protected(rel, protected_files()):
        return decision(
            "ask",
            f"{rel} is a protected file (AGENTS.md § 1): it needs the user's explicit confirmation.",
        )
    return None


# ── Bash parsing ────────────────────────────────────────────────────────────────────────


def split_commands(command: str) -> tuple[list[list[str]], dict[str, str]] | None:
    """Split a shell command into simple commands. Heredoc bodies become placeholders.

    Returns None when the command cannot be tokenised (unbalanced quotes and the like).
    """
    bodies: dict[str, str] = {}

    def stash(match: re.Match) -> str:
        key = f"__HEREDOC_{len(bodies)}__"
        bodies[key] = match.group(3)
        return f"<<{key}"

    # `-m "$(cat <<'EOF' … EOF)"` keeps its body inside quotes; shlex handles that itself.
    flattened = command if "$(cat <<" in command else HEREDOC.sub(stash, command)
    lexer = shlex.shlex(flattened, posix=True, punctuation_chars=";&|()<>\n")
    lexer.whitespace = " \t\r"
    lexer.whitespace_split = True
    try:
        tokens = list(lexer)
    except ValueError:
        return None

    commands: list[list[str]] = [[]]
    for token in tokens:
        if token and set(token) <= SEPARATOR_CHARS:
            commands.append([])
        else:
            commands[-1].append(token)
    return [c for c in commands if c], bodies


def strip_prefix(cmd: list[str]) -> list[str]:
    """Drop leading VAR=value assignments and harmless wrappers."""
    i = 0
    while i < len(cmd) and (re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", cmd[i]) or cmd[i] in {"env", "command", "time", "nohup"}):
        i += 1
    return cmd[i:]


def git_args(cmd: list[str]) -> list[str] | None:
    """Arguments after `git` and its global options, or None if this is not git."""
    if not cmd or Path(cmd[0]).name != "git":
        return None
    args = cmd[1:]
    while args and args[0].startswith("-"):
        takes_value = args[0] in {"-C", "-c", "--git-dir", "--work-tree", "--namespace"}
        args = args[2:] if takes_value else args[1:]
    return args


def commit_message(args: list[str], bodies: dict[str, str], cwd: str | None) -> str | None:
    parts: list[str] = []
    i = 0
    while i < len(args):
        arg = args[i]
        value = None
        if arg in {"-m", "--message", "-F", "--file"} and i + 1 < len(args):
            value, flag = args[i + 1], arg
            i += 1
        elif arg.startswith("--message="):
            value, flag = arg.split("=", 1)[1], "-m"
        elif arg.startswith("--file="):
            value, flag = arg.split("=", 1)[1], "-F"
        elif re.match(r"^-m.+", arg):
            value, flag = arg[2:], "-m"
        if value is not None:
            if flag in {"-F", "--file"}:
                if value in {"-", "/dev/stdin"}:
                    parts.append("\n".join(bodies.values()))
                else:
                    path = Path(value) if Path(value).is_absolute() else Path(cwd or PROJECT_DIR) / value
                    try:
                        parts.append(path.read_text(encoding="utf-8"))
                    except OSError:
                        pass
            else:
                inner = CAT_HEREDOC.match(value)
                parts.append(inner.group(2) if inner else value)
        i += 1
    return "\n\n".join(parts) if parts else None


def check_commit_message(message: str) -> str | None:
    lines = message.strip("\n").splitlines()
    if not lines:
        return "the commit message is empty."
    subject = lines[0]
    types = commit_types()
    pattern = rf"^({'|'.join(types)})(\([a-z0-9][a-z0-9/_-]*\))?!?: \S"
    if not re.match(pattern, subject):
        return (
            f"subject `{subject}` is not `<type>(<scope>): <description>` with a type from "
            f"AGENTS.md § 4 ({', '.join(types)}). The scope is lower-case and optional."
        )
    if len(subject) > SUBJECT_MAX:
        return f"the subject is {len(subject)} characters; keep it to {SUBJECT_MAX} or fewer."
    if subject.rstrip().endswith("."):
        return "the subject ends with a period; drop it."
    if len(lines) > 1 and lines[1].strip():
        return "the subject must be followed by a blank line before the body."
    if AI_ATTRIBUTION.search(message):
        return (
            "the message carries AI attribution (a Co-Authored-By trailer naming a tool, a "
            '"Generated with" line, or a tool link). AGENTS.md § 4 forbids it; remove the line.'
        )
    return None


def check_git(args: list[str], bodies: dict[str, str], cwd: str | None) -> dict | None:
    if not args:
        return None
    sub, rest = args[0], args[1:]
    flags = set(rest)

    def refuse(what: str, instead: str) -> dict:
        return decision("deny", f"Refused: {what} (AGENTS.md § 1). {instead}")

    if "--no-verify" in flags or (sub == "commit" and "-n" in flags):
        return refuse("--no-verify skips the checks that exist to catch this", "Fix what the hook reports.")
    if sub == "push":
        if flags & {"--force", "-f", "--force-with-lease", "--force-if-includes", "--mirror"} or any(
            a.startswith(("--force-with-lease=", "+")) for a in rest
        ):
            return refuse("a force push rewrites published history", "Ask the user; they run it themselves.")
        if flags & {"--delete", "-d"} or any(a.startswith(":") and len(a) > 1 for a in rest):
            return refuse("deleting a remote branch (rule 2)", "Ask the user.")
    if sub == "reset" and "--hard" in flags:
        return refuse("`git reset --hard` destroys uncommitted work (rule 4)", "Ask the user first.")
    if sub == "branch" and flags & {"-D", "-d", "--delete"}:
        return refuse("deleting a branch (rule 2)", "Ask the user.")
    if sub in {"filter-branch", "filter-repo"}:
        return refuse(f"`git {sub}` rewrites the whole history", "Only the user runs this, by hand.")
    if sub == "commit":
        message = commit_message(rest, bodies, cwd)
        if message is not None:
            problem = check_commit_message(message)
            if problem:
                return decision("deny", f"Commit message refused: {problem}")
    return None


def check_writes_protected(cmd: list[str], cwd: str | None) -> dict | None:
    protected = protected_files()
    targets: list[str] = []
    for i, token in enumerate(cmd):
        if token in WRITE_REDIRECTS and i + 1 < len(cmd):
            targets.append(cmd[i + 1])
    name = Path(cmd[0]).name if cmd else ""
    args = [a for a in cmd[1:] if not a.startswith("-")]
    if name in {"sed", "perl", "gsed"} and any(a.startswith("-i") or a == "--in-place" for a in cmd[1:]):
        targets += args
    elif name in {"tee", "rm", "truncate", "touch", "chmod", "unlink"}:
        targets += args
    elif name in {"mv", "cp", "ln", "install"} and args:
        targets += args if name == "mv" else args[-1:]
    for target in targets:
        rel = relative(target, cwd)
        if is_protected(rel, protected):
            return decision(
                "ask",
                f"This command writes {rel}, a protected file (AGENTS.md § 1); it needs the user's explicit confirmation.",
            )
    return None


def check_reads_env(cmd: list[str]) -> dict | None:
    if not cmd or Path(cmd[0]).name not in ENV_READERS:
        return None
    for arg in cmd[1:]:
        if ENV_FILE.search(arg) and not ENV_SAFE.search(arg):
            return decision(
                "deny",
                f"Refused: printing {arg} would echo .env values (AGENTS.md § 1 rule 6). "
                f"For key names only: grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' {arg}",
            )
    return None


def check_bash(tool_input: dict, cwd: str | None) -> dict | None:
    command = tool_input.get("command") or ""
    if not command.strip():
        return None
    parsed = split_commands(command)
    if parsed is None:
        if re.search(r"\bgit\b.*\b(commit|push|reset|branch|filter-)", command):
            return decision("ask", "The guard could not parse this git command, so it cannot check it against AGENTS.md § 1/§ 4.")
        return None
    commands, bodies = parsed
    for raw in commands:
        cmd = strip_prefix(raw)
        if not cmd:
            continue
        for check in (
            lambda: check_reads_env(cmd),
            lambda: check_writes_protected(cmd, cwd),
            lambda: (lambda a: check_git(a, bodies, cwd) if a is not None else None)(git_args(cmd)),
        ):
            result = check()
            if result:
                return result
    return None


# ── entry point ─────────────────────────────────────────────────────────────────────────


def evaluate(event: dict) -> dict | None:
    tool = event.get("tool_name") or ""
    tool_input = event.get("tool_input") or {}
    cwd = event.get("cwd")
    if tool in {"Edit", "Write", "MultiEdit", "NotebookEdit"}:
        return check_file_tool(tool_input, cwd)
    if tool == "Bash":
        return check_bash(tool_input, cwd)
    return None


def main() -> int:
    try:
        event = json.load(sys.stdin)
        result = evaluate(event)
    except Exception as exc:  # noqa: BLE001 — a broken guard must never block the session
        print(f"agent_guard: internal error, no decision made: {exc}", file=sys.stderr)
        return 0
    if result:
        json.dump(result, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
