#!/usr/bin/env python3
"""SessionStart hook: hands the agent the live facts AGENTS.md § 0 and § 4 tell it to check.

Everything here is read from the repository at session start — the branch, uncommitted
work, the installed versions, the next BUILD_ORDER task and the latest changelog entry —
so the agent starts from the current state instead of from prose that may have gone stale.
It is a convenience, not a substitute for the checks: AGENTS.md still says to verify.

Never fails the session: any error just leaves that line out.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or Path(__file__).resolve().parents[2])
MAX_DIRTY = 15


def git(*args: str) -> str:
    out = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=5)
    return out.stdout.strip()


def branch_line() -> str:
    head = git("status", "-sb").splitlines()[0].removeprefix("## ")
    dirty = git("status", "--porcelain").splitlines()
    line = f"Branch: {head}. Uncommitted paths: {len(dirty)}."
    if dirty:
        shown = "\n".join(f"  {d}" for d in dirty[:MAX_DIRTY])
        more = f"\n  … and {len(dirty) - MAX_DIRTY} more" if len(dirty) > MAX_DIRTY else ""
        line += f"\n{shown}{more}"
    return line


def versions_line() -> str:
    found = []
    lock = (ROOT / "backend/uv.lock").read_text(encoding="utf-8")
    for name in ("django", "djangorestframework"):
        m = re.search(rf'^name = "{name}"\nversion = "([^"]+)"', lock, re.M)
        if m:
            found.append(f"{name} {m.group(1)}")
    for name in ("next", "react"):
        pkg = ROOT / "frontend/node_modules" / name / "package.json"
        if pkg.exists():
            found.append(f"{name} {json.loads(pkg.read_text(encoding='utf-8'))['version']} (installed)")
    return "Locked/installed versions: " + ", ".join(found) + "."


def next_task_line() -> str:
    text = (ROOT / "documentation/planning/BUILD_ORDER.md").read_text(encoding="utf-8")
    open_tasks = re.findall(r"^### (.+?) ⬜\s*$", text, re.M)
    if not open_tasks:
        return "BUILD_ORDER.md: no unfinished task found."
    first = open_tasks[0]
    note = " — a question for the owner, not work: ask, don't code." if "DECISION" in first else ""
    return f"Next BUILD_ORDER task: {first}{note} ({len(open_tasks)} unfinished.)"


def changelog_line() -> str:
    text = (ROOT / "documentation/DAILY_CHANGES.md").read_text(encoding="utf-8")
    m = re.search(r"^## (\d{4}-\d{2}-\d{2})\s*\n+### (.+)$", text, re.M)
    return f"Latest DAILY_CHANGES entry: {m.group(1)} — {m.group(2)}." if m else ""


def main() -> int:
    lines = ["DjangoBaseX session context (generated by .claude/hooks/session_context.py):"]
    for build in (branch_line, versions_line, next_task_line, changelog_line):
        try:
            line = build()
        except Exception:  # noqa: BLE001 — a missing file must not break session start
            continue
        if line:
            lines.append(f"- {line}")
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "\n".join(lines)}}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
